### ISSUE TITLE
batch_size and positive pairs

### ISSUE THREAD

**Issue by ShengyuH** [XuyangBai/KPConv.pytorch#4]
hi Xuyang,

Thank you for making this nice work public. I am curious that do you have specific reasons for 
1. a small batch size(1 as reported in the paper)? 
2. only 64 positive pairs? This is rather small considering a fragment pair after 0.03m voxel downsampling, which is not difficult to mine around 2k correspondences. 

In addition, have you ever tried the hardest negative sampling proposed in FCGF? For me, KPConv and SparseConv are both fully convolutional networks, their downsampling/upsampling methods are also quite similar, so it's reasonable that the mining strategy worked on FCGF should also work on D3Feat. Or, do the detector loss requires a specific design choice of sampling in metric learning?

Best,
Shengyu

**Comment by XuyangBai** [comment]
Hi @ShengyuH 

I guess you are asking D3Feat instead of KPConv? For batch size, the reason is mainly the memory cost.  Some of the point cloud fragments are very large and I even have to skip some pair of pcd using batch size 1. For 64 positive pairs, the reason is the convergence issue. I found that using contrastive loss with the hardest mining (I also use "hardest negative sampling") is still sensitive to the number of correspondence.  If the hardest negative pairs are selected from a large number of correspondence, then the network might suffer from the collapse situation. FCGF tackles this problem by adding some random negative pair while I keep using only the hardest negative pair but use only 64. And after the conference, I found another loss which is more robust to the num of pos pair and neg pair called circle loss. Using circle loss I can increase the number of pos pairs and neg pairs without collapsing and achieve better performance than contrastive loss, you may have a try on that.

Best,
Xuyang

**Comment by ShengyuH** [comment]
hi @XuyangBai  

Thank you for your prompt reply! 

Yes I am asking about D3Feat, sorry to open this issue here by mistake. Yes I just noticed that you were skipping some frames. Thank you for your pointer of Circle loss, I'll test it. 

Best,
Shengyu
